recovery_behaviors: [{
    name: conservative_reset, 
    type: clear_costmap_recovery/ClearCostmapRecovery
  }, {
    name: rotate_recovery1,
    type: rotate_recovery/RotateRecovery
  }, {
    name: aggressive_reset,
    type: clear_costmap_recovery/ClearCostmapRecovery
  }, {
    name: rotate_recovery2,
    type: rotate_recovery/RotateRecovery
  }]